# Generated by Django 5.1.15 on 2026-07-20 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoPreparado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(help_text='Ex: upload_manual, e-mail, api', max_length=50, verbose_name='Origem')),
                ('data', models.DateField(verbose_name='Data do Lançamento')),
                ('dados_finais', models.JSONField(default=dict, help_text='Dados validados pelo usuário, prontos para lançamento.', verbose_name='Dados Finais')),
                ('status_exportacao', models.CharField(choices=[('pendente', 'Pendente'), ('exportado', 'Exportado')], default='pendente', max_length=15, verbose_name='Status de Exportação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_preparados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_preparados', to='documentos.documento', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Lançamento Preparado',
                'verbose_name_plural': 'Lançamentos Preparados',
                'db_table': 'lancamentos_preparados',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ValidacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_validacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Validação')),
                ('alteracoes_realizadas', models.JSONField(blank=True, default=dict, help_text='Dicionário com os campos alterados manualmente.', verbose_name='Alterações Realizadas')),
                ('decisao', models.CharField(choices=[('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], max_length=10, verbose_name='Decisão')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validacoes', to='documentos.documento', verbose_name='Documento')),
                ('usuario_validador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Validador')),
            ],
            options={
                'verbose_name': 'Log de Validação',
                'verbose_name_plural': 'Logs de Validação',
                'db_table': 'validacao_log',
                'ordering': ['-data_validacao'],
            },
        ),
    ]
