# Generated by Django 5.1.15 on 2026-07-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ollama', 'Ollama (Local)'), ('api', 'API Externa')], default='ollama', help_text='Ollama para desenvolvimento local, API para produção.', max_length=10, verbose_name='Provedor')),
                ('ollama_host', models.URLField(default='http://localhost:11434', help_text='URL do servidor Ollama local (ex: http://localhost:11434).', max_length=255, verbose_name='Host do Ollama')),
                ('ollama_model', models.CharField(default='llama3', help_text='Nome do modelo Ollama instalado localmente.', max_length=128, verbose_name='Modelo Ollama')),
                ('api_provider_name', models.CharField(default='groq', help_text='Identificador do provedor (ex: groq, openai, anthropic).', max_length=64, verbose_name='Nome do Provedor API')),
                ('api_base_url', models.URLField(default='https://api.groq.com/openai/v1', help_text='Endpoint base da API (compatível com OpenAI).', max_length=255, verbose_name='URL Base da API')),
                ('api_key', models.CharField(blank=True, default='', help_text='Chave secreta da API. Armazenada criptografada no banco.', max_length=255, verbose_name='Chave de API')),
                ('api_model', models.CharField(default='llama-3.3-70b-versatile', help_text='Nome do modelo a usar na API externa.', max_length=128, verbose_name='Modelo da API')),
                ('max_retries', models.PositiveIntegerField(default=2, help_text="Número máximo de tentativas de extração antes de marcar como 'precisa revisão'.", verbose_name='Máximo de Tentativas')),
                ('timeout_seconds', models.PositiveIntegerField(default=120, help_text='Tempo limite para chamadas ao LLM.', verbose_name='Timeout (segundos)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Configuração LLM',
                'verbose_name_plural': 'Configurações LLM',
                'ordering': ['-updated_at'],
            },
        ),
    ]
