# Generated by Django 5.1.15 on 2026-07-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='api_base_url',
            field=models.URLField(default='https://integrate.api.nvidia.com/v1', help_text='Endpoint base da API (compatível com OpenAI).', max_length=255, verbose_name='URL Base da API'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='api_model',
            field=models.CharField(default='meta/llama-3.3-70b-instruct', help_text='Nome do modelo a usar na API externa.', max_length=128, verbose_name='Modelo da API'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='api_provider_name',
            field=models.CharField(default='nvidia', help_text='Identificador do provedor (ex: nvidia, openai, anthropic).', max_length=64, verbose_name='Nome do Provedor API'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='provider',
            field=models.CharField(choices=[('ollama', 'Ollama (Local)'), ('api', 'API Externa')], default='api', help_text='Ollama para desenvolvimento local, API para produção.', max_length=10, verbose_name='Provedor'),
        ),
    ]
