# Generated by Django 5.1.15 on 2026-07-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_service', '0002_alter_llmconfig_api_base_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='Chave secreta da API. Em produção, lida da variável de ambiente LLM_API_KEY.', max_length=255, verbose_name='Chave de API'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='api_model',
            field=models.CharField(default='nvidia/nemotron-3-ultra-550b-a55b', help_text='Nome do modelo a usar na API externa.', max_length=128, verbose_name='Modelo da API'),
        ),
    ]
