# Generated by Django 5.1.15 on 2026-07-20 20:20

import apps.documentos.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosExtraidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campos_extraidos', models.JSONField(default=dict, verbose_name='Campos Extraídos')),
                ('provedor_llm_utilizado', models.CharField(choices=[('ollama', 'Ollama (Local)'), ('api', 'API Externa')], max_length=10, verbose_name='Provedor LLM Utilizado')),
                ('modelo_llm_utilizado', models.CharField(max_length=100, verbose_name='Modelo LLM Utilizado')),
                ('tempo_resposta_ms', models.IntegerField(blank=True, null=True, verbose_name='Tempo de Resposta (ms)')),
                ('tokens_utilizados', models.IntegerField(blank=True, null=True, verbose_name='Tokens Utilizados')),
                ('tentativas_realizadas', models.IntegerField(default=1, verbose_name='Tentativas Realizadas')),
                ('precisa_revisao', models.BooleanField(default=False, verbose_name='Precisa Revisão')),
                ('resposta_bruta_llm', models.TextField(blank=True, help_text='Armazenada apenas em caso de falha de validação.', null=True, verbose_name='Resposta Bruta do LLM')),
                ('data_extracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Extração')),
            ],
            options={
                'verbose_name': 'Dados Extraídos',
                'verbose_name_plural': 'Dados Extraídos',
                'db_table': 'dados_extraidos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('nota_fiscal', 'Nota Fiscal'), ('contrato', 'Contrato'), ('demonstrativo', 'Demonstrativo'), ('boleto', 'Boleto')], max_length=20, verbose_name='Tipo de Documento')),
                ('formato_arquivo', models.CharField(choices=[('pdf', 'PDF'), ('imagem', 'Imagem (JPG/PNG)'), ('xml', 'XML')], max_length=10, verbose_name='Formato do Arquivo')),
                ('arquivo_original', models.FileField(upload_to=apps.documentos.storage.get_upload_path, verbose_name='Arquivo Original')),
                ('origem', models.CharField(default='upload_manual', help_text='Ex: upload_manual, e-mail, api', max_length=50, verbose_name='Origem')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('validado', 'Validado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=15, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documentos',
                'ordering': ['-data_upload'],
            },
        ),
    ]
