# Generated by Django 5.1.15 on 2026-07-20 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='dadosextraidos',
            name='documento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_extraidos', to='documentos.documento', verbose_name='Documento'),
        ),
    ]
